name: 'ArgoCD Diff'
description: 'Diffs all ArgoCD apps in the repo, and provides the diff as a PR comment'
author: 'Quizlet'
inputs:
  argocd-server-url: 
    description: ArgoCD server url (without the protocol)
    required: true
  argocd-token: 
    description: ArgoCD token for a local or project-scoped user https://argoproj.github.io/argo-cd/operator-manual/user-management/#local-usersaccounts-v15
    required: true
  argocd-version: 
    description: ArgoCD Version
    default: v2.5.5
    required: false
  github-token: 
    description: Github Token
    required: true
  argocd-extra-cli-args: 
    description: Extra arguments to pass to the argocd CLI
    default: --grpc-web
    required: false
  argocd-env: 
    description: ArgoCD Environment
    default: prod
    required: false  
runs:
  using: 'node12'
  main: 'dist/index.js'
